kind: pipeline
type: docker
name: build

trigger:
  event:
  - push

steps:
- name: tag-commit-hash
  image: debian
  commands:
  - echo '${DRONE_COMMIT:0:8}' > .tags

- name: tag-dev
  image: debian
  when:
    branch:
    - dev
  commands:
  - sed -i '$s/$/,dev/' .tags

- name: tag-latest
  image: debian
  when:
    branch:
    - main
  commands:
  - sed -i '$s/$/,latest/' .tags

- name: build-image
  image: plugins/docker
  settings:
    repo: fugimuffi/fugi.dev
    username:
      from_secret: docker_username
    password:
      from_secret: docker_token

---
kind: pipeline
type: ssh
name: deploy

depends_on:
- build

trigger:
  branch:
  - main
  - dev
  event:
  - push

server:
  host:
    from_secret: ssh_host
  user:
    from_secret: ssh_user
  ssh_key:
    from_secret: ssh_key

steps:
- name: deploy-staging
  when:
    branch:
    - dev
  environment:
    DOCKER_USER:
      from_secret: docker_username
    DOCKER_PASS:
      from_secret: docker_token
  commands:
  - docker login -u $${DOCKER_USER} -p $${DOCKER_PASS}
  - docker-compose -p fugidev-staging -f docker-compose.staging.yml pull
  - docker-compose -p fugidev-staging -f docker-compose.staging.yml up --no-build -d

- name: deploy-production
  when:
    branch:
    - main
  environment:
    DOCKER_USER:
      from_secret: docker_username
    DOCKER_PASS:
      from_secret: docker_token
  commands:
  - docker login -u $${DOCKER_USER} -p $${DOCKER_PASS}
  - docker-compose -p fugidev -f docker-compose.yml pull
  - docker-compose -p fugidev -f docker-compose.yml up --no-build -d
